apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogo-componentes
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogo-componentes
  template:
    metadata:
      labels:
        app: catalogo-componentes
    spec:
      containers:
      - name: catalogo-componentes
        image: kdonjs/catalogo:1.0.6
        ports:
        - containerPort: 3200
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        env:
          - name: DB_PATH
            value: "/app/data/database.sqlite"
          - name: JWT_SECRET
            value: "dgsfdgfd45454as5d45s4a5das45d456as4d545as4d54as54d"
          - name: TOKEN_EXPIRATION
            value: "1h"
          - name: PORT
            value: "3200"
