version: '3.8'

services:
  app:
    image: catalogo-componentes:1.0.1
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/database.sqlite
    volumes:
      - sqlite-data:/app/data
    restart: always

volumes:
  sqlite-data: